name: Deploy to EC2

on:
  push:
    branches:
      - backend-ci-cd

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd app/backend
          mvn clean install

      - name: Build Docker image
        run: |
          cd app/backend
          docker build -t bounswe2023group5:latest .

      - name: Login to Docker Hub
        run: echo "bounswe2023group5" | docker login -u "bounswe2023group5" --password-stdin

      - name: Push to Docker Hub
        run: |
          docker tag bounswe2023group5:latest unaldenizzz/bounswe2023group5:latest
          docker push unaldenizzz/bounswe2023group5:latest

  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: "MIIEowIBAAKCAQEAjb17l0ytNYOo5c5oh/8Pym8pRVCyFEwnHxJfiUCBmaBkIgSsZa3OfRDpzXs5oar17Pyht/dFH0Qb7loxChV1zgac/ItVByv7od5GxVMIO01cMsK10rb68BqJAEqBfmR37dPvPxZ/NqHZO615oWv6gdG4b0XNoFy/gGuRDd9Pa+TD2eDQIR6VOofdAQp/2vWkDeqsGMlp29EIVx4+HbBt5KCctHrQGnrMdpirjQBHOZ34cZVo2neE+faewkBIw3yo2PRm4JrzOn+chQYwyvts2kd9iM+SBM4N8DG/xV9cKvGcKFE76DZAOATpXpNxI6RJGRsxkiGMWMjzOhGODqjYOQIDAQABAoIBAEA/suUrWZxXWNkKjjGPOY4ug0urP32Z42XfQzUI63ZC0QDmk2rntSDV6NU+1SnmP+Gzxm6IhGmeyvZpJa+HeMXyE3kag2lj04VVJ0lM0P9omrFbt2WTkf4CWTWrkDVFv2Mr3VgAj5upE7pMcUTtmDj+Ypb10jattBS3LaJXJj4mX9CzoI+okU2pyNqi91MNhS0v4QWhLfkGFwPiZ5OWZ01gbhyZ58XZnN1t7E2O9M7VA3V0V4cADh8szVxW06Z4E51dKQI03klD+N/LHtJ5GnwtZhSU3Ki38ABZsT3Owd26iUWCV7GnaeGi0CI45/LJxTUFjzAULayDPgcNd/V4zIECgYEA0yX1viEXknnHgqiyi05B8ADsa5c2pTTiqRNxCwzpPNnDL9udjCrHygvqC5cw7hZue81rr5Oop8My9/kEKxTHwNuX1U8uu/q7rsl3cLxgrglIvyPTNsjrP76TpfFiRWiWKhtndXTjIo3P3gCV8CNmnucVLoUNrD1GiuzOqaVUfrECgYEAq9ktLnYTzt1wMnWt2KD2ieV/qvHxmToMa8b15IjLTZXifPHAYooG1ZRbsT4km0dPw/kOQFXvdFZFPtT8y287hy1LR1nbsAFCqjva3zRFrrMB2AO0DbKCYMiZSYe9s48bAP0NPATfjypeh/D+7KCkCm3FRoVFdm8KHqd01J23pAkCgYBmakckDZENbxwieAkCINdCvm/uT84lm91E/TUbkwuehFF0aSWl0ypNCjJfpNoK4b59NkpBQ3HOzZNvS82Fx/KLzPd8c4fLjfZy9S2F9Rk/0SkD7TCJpjLVHG8pUkfEOtJ7YgdwpV12aSqmF8qiS8l+0b8obUkQfjg1Ml+bUaIGQQKBgElto8udcntKzR0SgXT12kIzyOhfNw906UfIHNtIxC3jpIIkvkKcnaz3FnLWjce3odKoAbnlvkpkbnQZh+bZIYNyDB9xutgqwbSBnNUQvdGW9Wu6sV3E78axECaGFL27oRs8BUKnBmti/D9z70lmnpFCNDAc1AB2E8njXZ1XwtcZAoGBALQOtuP5VdAHwKlBTm8OReHYU3Sgxn/P7QNju5GBmKmx00jVBvE2EEl27DOhZvZy3sh5QLJI1xW5faail8Vbb0T9KAFfmCF61x8Oq7F5cCsP9eJUqhtNH8WJPXzXlamrRObd7iimDWvo4VcQXFLJ6of4Wj0rccA2AsbVd5RuiCr8"
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@ec2-16-16-166-22.eu-north-1.compute.amazonaws.com 'updateswe'
